yamlname: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install board platform
        run: arduino-cli core install arduino:avr
      - name: Install libraries
        run: |
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install "MFRC522"
      - name: Compile sketch
        run: arduino-cli compile --fqbn arduino:avr:uno src/GlassTag/GlassTag.ino
